from mapping import AlumnoMapping
from mapping import AreaMapping
from mapping import AutoridadMapping
from mapping import CargoMapping
from mapping import CategoriaCargoMapping
from mapping import CursadaMapping
from mapping import DepartamentoMapping
from mapping import EspecialidadMapping
from mapping import EvaluacionMapping
from mapping import FacultadMapping
from mapping import GradoMapping
from mapping import GrupoMapping
from mapping import InscripcionMapping
from mapping import MateriaMapping
from mapping import NotaMapping
from mapping import OrientacionMapping
from mapping import PlanMapping
from mapping import TipoDedicacionMapping
from mapping import TipoDocumentoMapping
from mapping import TipoEspecialidadMapping
from mapping import UniversidadMapping
